import { env } from "@/env.mjs";

export const siteConfig = {
  name: "Shendi Teuku Maulana Efendi",
  title: "Shendi Teuku Maulana Efendi | AI Engineer & MLOps Enthusiast",
  description:
    "Hi, I'm Shendi — an AI Engineer from Indonesia specializing in building end-to-end machine learning systems, from data pipelines to model deployment and monitoring. Passionate about integrating AI into modern web applications with Next.js and FastAPI.",
  keywords: [
    "Shendi Teuku Maulana Efendi",
    "AI Engineer",
    "Machine Learning Engineer",
    "MLOps",
    "Artificial Intelligence",
    "Deep Learning",
    "Data Science",
    "TensorFlow",
    "PyTorch",
    "ONNX",
    "TFX",
    "FastAPI",
    "Next.js",
    "React",
    "PostgreSQL",
    "Prometheus",
    "Grafana",
    "MLflow",
    "Cloud Deployment",
    "AI Portfolio",
    "Model Deployment",
    "Web AI Integration",
    "End-to-End ML Pipeline",
    "Tech Enthusiast",
  ],
  creator: "Shendi Teuku Maulana Efendi",
  url: "#",
  contact: {
    email: "shendyteuku2@gmail.com",
    linkedin: "https://www.linkedin.com/in/shendyeff",
    github: "https://github.com/covryzne",
  },
  links: {
    contactForm: "/#contact",
    linkedin: "https://www.linkedin.com/in/shendyeff",
    github: "https://github.com/covryzne",
    dicoding: "https://www.dicoding.com/users/shendyeff",
    mailTo: "mailto:shendyteuku2@gmail.com",
    cvPdf: "/shendi-teuku-maulana-efendi-cv.pdf",
    footer: "#",
  },
};
